# Site settings
title: Junior CS Student Ramblings
email: DjSky09@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a junior in Computer Science student. I enjoy learning about programming languages. The primary language
  I use for school is C++, but I am eager to learn Ruby and Python as I've heard they're fun to program in. Last summer
  I took my first database class and I instantly feel in love with SQL, so I hope to study more about backend and be hired as a DBA.
  My blog posts will mainly be about school struggles and achievements. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: Celestula28
github_username:  Celestula

# Build settings
markdown: kramdown

paginate: 4

author: Heather G

gems: [jekyll-paginate]
